apiVersion: apps/v1
kind: Deployment
metadata:
  name: dndevops-identity
  namespace: dndevops
  labels:
    app: dndevops-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dndevops-identity
  template:
    metadata:
      labels:
        app: dndevops-identity
    spec:
      containers:
        - name: dndevops-identity
          image: ghcr.io/roguebit2002/dndevops:0.0.1-dev
          ports:
            - containerPort: 8000
          env:
            - name: DNDEVOPS_DEPLOYMENT
              value: identity
            - name: DNDEVOPS_ADMINS
              value: admin@dndevops.dev
            - name: DNDEVOPS_JWT_SECRET
              value: Youshouldprobablynotdothis
            - name: DNDEVOPS_SMTP_URI
              value: smtp://user:password@smtp-service
            - name: DNDEVOPS_SMTP_SENDER
              value: dndevops@company.com
            - name: DNDEVOPS_AMQP_URI
              value: amqp://user:password@amqp-service
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-login
                  key: USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-login
                  key: PASSWORD
            - name: DNDEVOPS_IDENTITY_POSTGRES_URI
              value: postgres://${DB_USER}:${DB_PASS}@dndevops-demo-db.postgres.database.azure.com/
            

