apiVersion: v1
data:
    foo: ENC[AES256_GCM,data:1nJrAA==,iv:tOQYO8bT4RcRD7nhnDTbt8pS+yzTkWDbKokezZZv7bA=,tag:zg9g2bDlM3ZEonS2XkauWg==,type:str]
kind: Secret
metadata:
    name: sopstest
sops:
    age:
        - recipient: age19vsak44nzqfuevtnwn5e0ll4krc96ysrxf9emt984gr46dpn89ss9zy0sy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdU82NDdMUHRGV3BiU045
            NGVWZXd6eVQ4SWlYR3dORFdIZUU2U1pOSkdVCjFJMnFYSzkxQityUXljYWJteTMz
            RUNhdHFUVDNyekR4cVVlQ2loS1pHdjQKLS0tIHpmM0g1eHdBblIwaCtFRDhqK0hp
            bEZ3QVUyUGY3N2ErNjllY1NwdUJ4NXMKpCIzOtlwNYWXNz6lvAP66uCuL2HA+Azc
            Nu7pgen2mK5Au2gwpY26I5VRRBsgy3FI8tpvo9TF95TCwT7iFKV24Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T17:57:25Z"
    mac: ENC[AES256_GCM,data:tidRm4Oq1fvLld6P63cbRYyMJ0BTJqWAJml5nrZK7MhHsD2PZApMCCWFIfr/S0qdhLfCafNXlbawPqVDfcjKpd1Qw5aN8lq++Sn/k0LfXjjDJHAwRBXaIb05ism0qIjUKEmpRIL9m2brjZBNM+J8KF0OJnzcBz7aV12aZZ0J5os=,iv:Sw2iqLCsGBhoWG06tNbC9q9plH/FVELGrDmZcpN6UXA=,tag:gRlGAl8VMPdLdo0+swgsag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
